const categories = {
  en: { emergency_fund: 'Emergency fund', home: 'Home', vehicle: 'Vehicle', education: 'Education', travel: 'Travel', family: 'Family', health: 'Health', business: 'Business', debt_payoff: 'Debt payoff', technology: 'Technology', wedding: 'Wedding', religious_event: 'Religious event', personal: 'Personal', other: 'Other' },
  fr: { emergency_fund: 'Fonds d’urgence', home: 'Logement', vehicle: 'Véhicule', education: 'Éducation', travel: 'Voyage', family: 'Famille', health: 'Santé', business: 'Entreprise', debt_payoff: 'Remboursement de dette', technology: 'Technologie', wedding: 'Mariage', religious_event: 'Événement religieux', personal: 'Personnel', other: 'Autre' },
  ar: { emergency_fund: 'صندوق الطوارئ', home: 'المنزل', vehicle: 'المركبة', education: 'التعليم', travel: 'السفر', family: 'العائلة', health: 'الصحة', business: 'العمل', debt_payoff: 'سداد الدين', technology: 'التقنية', wedding: 'الزفاف', religious_event: 'مناسبة دينية', personal: 'شخصي', other: 'أخرى' },
  es: { emergency_fund: 'Fondo de emergencia', home: 'Hogar', vehicle: 'Vehículo', education: 'Educación', travel: 'Viajes', family: 'Familia', health: 'Salud', business: 'Negocio', debt_payoff: 'Pago de deudas', technology: 'Tecnología', wedding: 'Boda', religious_event: 'Evento religioso', personal: 'Personal', other: 'Otro' },
  de: { emergency_fund: 'Notfallfonds', home: 'Wohnen', vehicle: 'Fahrzeug', education: 'Bildung', travel: 'Reisen', family: 'Familie', health: 'Gesundheit', business: 'Unternehmen', debt_payoff: 'Schuldentilgung', technology: 'Technik', wedding: 'Hochzeit', religious_event: 'Religiöser Anlass', personal: 'Persönlich', other: 'Sonstiges' },
  pt: { emergency_fund: 'Fundo de emergência', home: 'Casa', vehicle: 'Veículo', education: 'Educação', travel: 'Viagem', family: 'Família', health: 'Saúde', business: 'Negócio', debt_payoff: 'Pagamento de dívidas', technology: 'Tecnologia', wedding: 'Casamento', religious_event: 'Evento religioso', personal: 'Pessoal', other: 'Outro' },
  it: { emergency_fund: 'Fondo di emergenza', home: 'Casa', vehicle: 'Veicolo', education: 'Istruzione', travel: 'Viaggi', family: 'Famiglia', health: 'Salute', business: 'Attività', debt_payoff: 'Rimborso debiti', technology: 'Tecnologia', wedding: 'Matrimonio', religious_event: 'Evento religioso', personal: 'Personale', other: 'Altro' },
  nl: { emergency_fund: 'Noodfonds', home: 'Wonen', vehicle: 'Voertuig', education: 'Opleiding', travel: 'Reizen', family: 'Familie', health: 'Gezondheid', business: 'Bedrijf', debt_payoff: 'Schuld aflossen', technology: 'Technologie', wedding: 'Bruiloft', religious_event: 'Religieuze gebeurtenis', personal: 'Persoonlijk', other: 'Overig' },
  tr: { emergency_fund: 'Acil durum fonu', home: 'Ev', vehicle: 'Araç', education: 'Eğitim', travel: 'Seyahat', family: 'Aile', health: 'Sağlık', business: 'İş', debt_payoff: 'Borç ödeme', technology: 'Teknoloji', wedding: 'Düğün', religious_event: 'Dini etkinlik', personal: 'Kişisel', other: 'Diğer' },
};

const vectors = {
  en: { shield: 'Shield', umbrella: 'Umbrella', medical_cross: 'Medical', home: 'Home', key: 'Key', car: 'Car', maintenance: 'Maintenance', graduation_cap: 'Graduation', book: 'Book', school: 'School', airplane: 'Airplane', suitcase: 'Suitcase', map: 'Map', family: 'Family', gift: 'Gift', wallet: 'Wallet', piggy_bank: 'Savings', debt_free: 'Debt free', target: 'Target', briefcase: 'Briefcase', store: 'Store', laptop: 'Laptop', heart: 'Heart', celebration: 'Celebration', star: 'Star', custom_goal: 'Custom' },
  fr: { shield: 'Bouclier', umbrella: 'Parapluie', medical_cross: 'Médical', home: 'Maison', key: 'Clé', car: 'Voiture', maintenance: 'Entretien', graduation_cap: 'Diplôme', book: 'Livre', school: 'École', airplane: 'Avion', suitcase: 'Valise', map: 'Carte', family: 'Famille', gift: 'Cadeau', wallet: 'Portefeuille', piggy_bank: 'Épargne', debt_free: 'Sans dette', target: 'Cible', briefcase: 'Mallette', store: 'Boutique', laptop: 'Ordinateur', heart: 'Cœur', celebration: 'Célébration', star: 'Étoile', custom_goal: 'Personnalisé' },
  ar: { shield: 'درع', umbrella: 'مظلة', medical_cross: 'طبي', home: 'منزل', key: 'مفتاح', car: 'سيارة', maintenance: 'صيانة', graduation_cap: 'تخرج', book: 'كتاب', school: 'مدرسة', airplane: 'طائرة', suitcase: 'حقيبة', map: 'خريطة', family: 'عائلة', gift: 'هدية', wallet: 'محفظة', piggy_bank: 'ادخار', debt_free: 'بلا ديون', target: 'هدف', briefcase: 'حقيبة عمل', store: 'متجر', laptop: 'حاسوب', heart: 'قلب', celebration: 'احتفال', star: 'نجمة', custom_goal: 'مخصص' },
  es: { shield: 'Escudo', umbrella: 'Paraguas', medical_cross: 'Médico', home: 'Casa', key: 'Llave', car: 'Coche', maintenance: 'Mantenimiento', graduation_cap: 'Graduación', book: 'Libro', school: 'Escuela', airplane: 'Avión', suitcase: 'Maleta', map: 'Mapa', family: 'Familia', gift: 'Regalo', wallet: 'Cartera', piggy_bank: 'Ahorros', debt_free: 'Sin deudas', target: 'Objetivo', briefcase: 'Maletín', store: 'Tienda', laptop: 'Portátil', heart: 'Corazón', celebration: 'Celebración', star: 'Estrella', custom_goal: 'Personalizado' },
  de: { shield: 'Schild', umbrella: 'Regenschirm', medical_cross: 'Medizin', home: 'Haus', key: 'Schlüssel', car: 'Auto', maintenance: 'Wartung', graduation_cap: 'Abschluss', book: 'Buch', school: 'Schule', airplane: 'Flugzeug', suitcase: 'Koffer', map: 'Karte', family: 'Familie', gift: 'Geschenk', wallet: 'Geldbörse', piggy_bank: 'Sparen', debt_free: 'Schuldenfrei', target: 'Ziel', briefcase: 'Aktentasche', store: 'Geschäft', laptop: 'Laptop', heart: 'Herz', celebration: 'Feier', star: 'Stern', custom_goal: 'Benutzerdefiniert' },
  pt: { shield: 'Escudo', umbrella: 'Guarda-chuva', medical_cross: 'Médico', home: 'Casa', key: 'Chave', car: 'Carro', maintenance: 'Manutenção', graduation_cap: 'Graduação', book: 'Livro', school: 'Escola', airplane: 'Avião', suitcase: 'Mala', map: 'Mapa', family: 'Família', gift: 'Presente', wallet: 'Carteira', piggy_bank: 'Poupança', debt_free: 'Sem dívidas', target: 'Objetivo', briefcase: 'Pasta', store: 'Loja', laptop: 'Portátil', heart: 'Coração', celebration: 'Celebração', star: 'Estrela', custom_goal: 'Personalizado' },
  it: { shield: 'Scudo', umbrella: 'Ombrello', medical_cross: 'Medico', home: 'Casa', key: 'Chiave', car: 'Auto', maintenance: 'Manutenzione', graduation_cap: 'Laurea', book: 'Libro', school: 'Scuola', airplane: 'Aereo', suitcase: 'Valigia', map: 'Mappa', family: 'Famiglia', gift: 'Regalo', wallet: 'Portafoglio', piggy_bank: 'Risparmi', debt_free: 'Senza debiti', target: 'Obiettivo', briefcase: 'Valigetta', store: 'Negozio', laptop: 'Portatile', heart: 'Cuore', celebration: 'Festa', star: 'Stella', custom_goal: 'Personalizzato' },
  nl: { shield: 'Schild', umbrella: 'Paraplu', medical_cross: 'Medisch', home: 'Huis', key: 'Sleutel', car: 'Auto', maintenance: 'Onderhoud', graduation_cap: 'Diploma', book: 'Boek', school: 'School', airplane: 'Vliegtuig', suitcase: 'Koffer', map: 'Kaart', family: 'Familie', gift: 'Cadeau', wallet: 'Portemonnee', piggy_bank: 'Sparen', debt_free: 'Schuldenvrij', target: 'Doel', briefcase: 'Aktetas', store: 'Winkel', laptop: 'Laptop', heart: 'Hart', celebration: 'Viering', star: 'Ster', custom_goal: 'Aangepast' },
  tr: { shield: 'Kalkan', umbrella: 'Şemsiye', medical_cross: 'Sağlık', home: 'Ev', key: 'Anahtar', car: 'Araba', maintenance: 'Bakım', graduation_cap: 'Mezuniyet', book: 'Kitap', school: 'Okul', airplane: 'Uçak', suitcase: 'Valiz', map: 'Harita', family: 'Aile', gift: 'Hediye', wallet: 'Cüzdan', piggy_bank: 'Birikim', debt_free: 'Borçsuz', target: 'Hedef', briefcase: 'Evrak çantası', store: 'Mağaza', laptop: 'Dizüstü bilgisayar', heart: 'Kalp', celebration: 'Kutlama', star: 'Yıldız', custom_goal: 'Özel' },
};

const colors = {
  en: { pocket_blue: 'Pocket blue', deep_navy: 'Deep navy', positive_lime: 'Positive lime', teal: 'Teal', violet: 'Violet', amber: 'Amber', coral: 'Coral', rose: 'Rose', sky: 'Sky blue', neutral: 'Neutral' },
  fr: { pocket_blue: 'Bleu Pocket', deep_navy: 'Bleu marine', positive_lime: 'Citron vert', teal: 'Sarcelle', violet: 'Violet', amber: 'Ambre', coral: 'Corail', rose: 'Rose', sky: 'Bleu ciel', neutral: 'Neutre' },
  ar: { pocket_blue: 'أزرق بوكيت', deep_navy: 'كحلي داكن', positive_lime: 'ليموني', teal: 'أزرق مخضر', violet: 'بنفسجي', amber: 'كهرماني', coral: 'مرجاني', rose: 'وردي', sky: 'أزرق سماوي', neutral: 'محايد' },
  es: { pocket_blue: 'Azul Pocket', deep_navy: 'Azul marino', positive_lime: 'Lima positiva', teal: 'Verde azulado', violet: 'Violeta', amber: 'Ámbar', coral: 'Coral', rose: 'Rosa', sky: 'Azul cielo', neutral: 'Neutro' },
  de: { pocket_blue: 'Pocket-Blau', deep_navy: 'Dunkelblau', positive_lime: 'Positives Limettengrün', teal: 'Petrol', violet: 'Violett', amber: 'Bernstein', coral: 'Koralle', rose: 'Rosa', sky: 'Himmelblau', neutral: 'Neutral' },
  pt: { pocket_blue: 'Azul Pocket', deep_navy: 'Azul-marinho', positive_lime: 'Lima positiva', teal: 'Verde-azulado', violet: 'Violeta', amber: 'Âmbar', coral: 'Coral', rose: 'Rosa', sky: 'Azul-céu', neutral: 'Neutro' },
  it: { pocket_blue: 'Blu Pocket', deep_navy: 'Blu navy', positive_lime: 'Lime positivo', teal: 'Verde acqua', violet: 'Viola', amber: 'Ambra', coral: 'Corallo', rose: 'Rosa', sky: 'Azzurro cielo', neutral: 'Neutro' },
  nl: { pocket_blue: 'Pocket-blauw', deep_navy: 'Donker marineblauw', positive_lime: 'Positief lime', teal: 'Blauwgroen', violet: 'Violet', amber: 'Amber', coral: 'Koraal', rose: 'Roze', sky: 'Hemelsblauw', neutral: 'Neutraal' },
  tr: { pocket_blue: 'Pocket mavisi', deep_navy: 'Koyu lacivert', positive_lime: 'Pozitif limon yeşili', teal: 'Camgöbeği', violet: 'Menekşe', amber: 'Kehribar', coral: 'Mercan', rose: 'Gül', sky: 'Gök mavisi', neutral: 'Nötr' },
};

export const goalTranslations = {
  en: { title: 'Goals', active: 'Active', completed: 'Completed', archived: 'Archived', add: 'Create goal', edit: 'Edit goal', empty: 'Create a goal that fits your plan.', description: 'Description (optional)', name: 'Goal title', target: 'Target amount', saved: 'Already saved', date: 'Target date', next: 'Next', back: 'Back', save: 'Save goal', update: 'Update goal', chooseCategory: 'Choose a category', chooseStyle: 'Choose an icon and color', enterDetails: 'Enter goal details', review: 'Review and reminder', priority: 'Priority', reminder: 'Contribution reminder', noReminder: 'No reminder', weekly: 'Weekly', monthly: 'Monthly', once: 'One time', contribution: 'Add contribution', contributionAmount: 'Contribution amount', contributionNote: 'Note (optional)', history: 'Contribution history', noHistory: 'No contributions recorded yet.', pause: 'Pause', resume: 'Resume', archive: 'Archive', delete: 'Delete', markComplete: 'Mark complete', deleteConfirm: 'Delete this goal and its contribution history?', savedOf: '{{saved}} saved of {{target}}', due: 'Due {{date}}', requiredMonthly: 'May need {{amount}} per month', requiredWeekly: '{{amount}} per week', projected: 'Projected {{date}}', statuses: { on_track: 'On track', adjustment_needed: 'Slight adjustment needed', unrealistic: 'Currently unrealistic', completed: 'Completed', paused: 'Paused', active: 'Active', archived: 'Archived' }, priorities: { essential: 'High', important: 'Medium', optional: 'Low' }, categories: categories.en, validation: { title: 'Enter a goal title.', target: 'Enter a target amount greater than zero.', saved: 'Enter a valid saved amount.', date: 'Choose today or a future date.', contribution: 'Enter a valid contribution amount.' }, completedTitle: 'Goal completed!', completedBody: 'You reached your goal of {{amount}}.', createAnother: 'Create another goal', returnGoals: 'Return to goals' },
  fr: { title: 'Objectifs', active: 'Actifs', completed: 'Terminés', archived: 'Archivés', add: 'Créer un objectif', edit: 'Modifier l’objectif', empty: 'Créez un objectif adapté à votre plan.', description: 'Description (facultatif)', name: 'Nom de l’objectif', target: 'Montant cible', saved: 'Déjà épargné', date: 'Date cible', next: 'Suivant', back: 'Retour', save: 'Enregistrer', update: 'Mettre à jour', chooseCategory: 'Choisissez une catégorie', chooseStyle: 'Choisissez une icône et une couleur', enterDetails: 'Saisissez les détails', review: 'Vérification et rappel', priority: 'Priorité', reminder: 'Rappel de contribution', noReminder: 'Aucun rappel', weekly: 'Hebdomadaire', monthly: 'Mensuel', once: 'Une fois', contribution: 'Ajouter une contribution', contributionAmount: 'Montant de la contribution', contributionNote: 'Note (facultatif)', history: 'Historique des contributions', noHistory: 'Aucune contribution enregistrée.', pause: 'Mettre en pause', resume: 'Reprendre', archive: 'Archiver', delete: 'Supprimer', markComplete: 'Marquer comme terminé', deleteConfirm: 'Supprimer cet objectif et son historique ?', savedOf: '{{saved}} épargné sur {{target}}', due: 'Échéance {{date}}', requiredMonthly: 'Peut nécessiter {{amount}} par mois', requiredWeekly: '{{amount}} par semaine', projected: 'Projection {{date}}', statuses: { on_track: 'En bonne voie', adjustment_needed: 'Léger ajustement nécessaire', unrealistic: 'Actuellement irréaliste', completed: 'Terminé', paused: 'En pause', active: 'Actif', archived: 'Archivé' }, priorities: { essential: 'Haute', important: 'Moyenne', optional: 'Faible' }, categories: categories.fr, validation: { title: 'Saisissez un nom.', target: 'Saisissez un montant cible supérieur à zéro.', saved: 'Saisissez un montant épargné valide.', date: 'Choisissez aujourd’hui ou une date future.', contribution: 'Saisissez une contribution valide.' }, completedTitle: 'Objectif atteint !', completedBody: 'Vous avez atteint votre objectif de {{amount}}.', createAnother: 'Créer un autre objectif', returnGoals: 'Retour aux objectifs' },
  ar: { title: 'الأهداف', active: 'النشطة', completed: 'المكتملة', archived: 'المؤرشفة', add: 'إنشاء هدف', edit: 'تعديل الهدف', empty: 'أنشئ هدفًا يناسب خطتك.', description: 'الوصف (اختياري)', name: 'اسم الهدف', target: 'المبلغ المستهدف', saved: 'المبلغ المدخر', date: 'التاريخ المستهدف', next: 'التالي', back: 'رجوع', save: 'حفظ الهدف', update: 'تحديث الهدف', chooseCategory: 'اختر فئة', chooseStyle: 'اختر أيقونة ولونًا', enterDetails: 'أدخل تفاصيل الهدف', review: 'المراجعة والتذكير', priority: 'الأولوية', reminder: 'تذكير بالمساهمة', noReminder: 'بدون تذكير', weekly: 'أسبوعي', monthly: 'شهري', once: 'مرة واحدة', contribution: 'إضافة مساهمة', contributionAmount: 'مبلغ المساهمة', contributionNote: 'ملاحظة (اختياري)', history: 'سجل المساهمات', noHistory: 'لا توجد مساهمات بعد.', pause: 'إيقاف مؤقت', resume: 'استئناف', archive: 'أرشفة', delete: 'حذف', markComplete: 'تحديد كمكتمل', deleteConfirm: 'حذف هذا الهدف وسجل مساهماته؟', savedOf: 'تم ادخار {{saved}} من {{target}}', due: 'الاستحقاق {{date}}', requiredMonthly: 'قد يحتاج إلى {{amount}} شهريًا', requiredWeekly: '{{amount}} أسبوعيًا', projected: 'التاريخ المتوقع {{date}}', statuses: { on_track: 'على المسار', adjustment_needed: 'يحتاج تعديلًا بسيطًا', unrealistic: 'غير واقعي حاليًا', completed: 'مكتمل', paused: 'متوقف مؤقتًا', active: 'نشط', archived: 'مؤرشف' }, priorities: { essential: 'عالية', important: 'متوسطة', optional: 'منخفضة' }, categories: categories.ar, validation: { title: 'أدخل اسم الهدف.', target: 'أدخل مبلغًا مستهدفًا أكبر من صفر.', saved: 'أدخل مبلغ ادخار صالحًا.', date: 'اختر اليوم أو تاريخًا مستقبليًا.', contribution: 'أدخل مبلغ مساهمة صالحًا.' }, completedTitle: 'اكتمل الهدف!', completedBody: 'لقد حققت هدفك البالغ {{amount}}.', createAnother: 'إنشاء هدف آخر', returnGoals: 'العودة إلى الأهداف' },
  es: { title: 'Objetivos', active: 'Activos', completed: 'Completados', archived: 'Archivados', add: 'Crear objetivo', edit: 'Editar objetivo', empty: 'Crea un objetivo que encaje con tu plan.', description: 'Descripción (opcional)', name: 'Nombre del objetivo', target: 'Importe objetivo', saved: 'Ya ahorrado', date: 'Fecha objetivo', next: 'Siguiente', back: 'Atrás', save: 'Guardar objetivo', update: 'Actualizar objetivo', chooseCategory: 'Elige una categoría', chooseStyle: 'Elige un icono y un color', enterDetails: 'Introduce los detalles', review: 'Revisión y recordatorio', priority: 'Prioridad', reminder: 'Recordatorio de aportación', noReminder: 'Sin recordatorio', weekly: 'Semanal', monthly: 'Mensual', once: 'Una vez', contribution: 'Añadir aportación', contributionAmount: 'Importe de la aportación', contributionNote: 'Nota (opcional)', history: 'Historial de aportaciones', noHistory: 'Aún no hay aportaciones.', pause: 'Pausar', resume: 'Reanudar', archive: 'Archivar', delete: 'Eliminar', markComplete: 'Marcar como completado', deleteConfirm: '¿Eliminar este objetivo y su historial de aportaciones?', savedOf: '{{saved}} ahorrado de {{target}}', due: 'Vence {{date}}', requiredMonthly: 'Puede requerir {{amount}} al mes', requiredWeekly: '{{amount}} por semana', projected: 'Previsto para {{date}}', statuses: { on_track: 'En buen camino', adjustment_needed: 'Necesita un pequeño ajuste', unrealistic: 'Actualmente no es realista', completed: 'Completado', paused: 'En pausa', active: 'Activo', archived: 'Archivado' }, priorities: { essential: 'Alta', important: 'Media', optional: 'Baja' }, categories: categories.es, validation: { title: 'Introduce un nombre para el objetivo.', target: 'Introduce un importe objetivo mayor que cero.', saved: 'Introduce un importe ahorrado válido.', date: 'Elige hoy o una fecha futura.', contribution: 'Introduce un importe de aportación válido.' }, completedTitle: '¡Objetivo completado!', completedBody: 'Has alcanzado tu objetivo de {{amount}}.', createAnother: 'Crear otro objetivo', returnGoals: 'Volver a objetivos' },
  de: { title: 'Ziele', active: 'Aktiv', completed: 'Abgeschlossen', archived: 'Archiviert', add: 'Ziel erstellen', edit: 'Ziel bearbeiten', empty: 'Erstelle ein Ziel, das zu deinem Plan passt.', description: 'Beschreibung (optional)', name: 'Zielname', target: 'Zielbetrag', saved: 'Bereits gespart', date: 'Zieldatum', next: 'Weiter', back: 'Zurück', save: 'Ziel speichern', update: 'Ziel aktualisieren', chooseCategory: 'Kategorie wählen', chooseStyle: 'Symbol und Farbe wählen', enterDetails: 'Zieldetails eingeben', review: 'Prüfung und Erinnerung', priority: 'Priorität', reminder: 'Beitragserinnerung', noReminder: 'Keine Erinnerung', weekly: 'Wöchentlich', monthly: 'Monatlich', once: 'Einmalig', contribution: 'Beitrag hinzufügen', contributionAmount: 'Beitragsbetrag', contributionNote: 'Notiz (optional)', history: 'Beitragsverlauf', noHistory: 'Noch keine Beiträge erfasst.', pause: 'Pausieren', resume: 'Fortsetzen', archive: 'Archivieren', delete: 'Löschen', markComplete: 'Als abgeschlossen markieren', deleteConfirm: 'Dieses Ziel und seinen Beitragsverlauf löschen?', savedOf: '{{saved}} von {{target}} gespart', due: 'Fällig {{date}}', requiredMonthly: 'Möglicherweise {{amount}} pro Monat nötig', requiredWeekly: '{{amount}} pro Woche', projected: 'Voraussichtlich {{date}}', statuses: { on_track: 'Im Plan', adjustment_needed: 'Kleine Anpassung nötig', unrealistic: 'Derzeit unrealistisch', completed: 'Abgeschlossen', paused: 'Pausiert', active: 'Aktiv', archived: 'Archiviert' }, priorities: { essential: 'Hoch', important: 'Mittel', optional: 'Niedrig' }, categories: categories.de, validation: { title: 'Gib einen Zielnamen ein.', target: 'Gib einen Zielbetrag größer als null ein.', saved: 'Gib einen gültigen Sparbetrag ein.', date: 'Wähle heute oder ein zukünftiges Datum.', contribution: 'Gib einen gültigen Beitragsbetrag ein.' }, completedTitle: 'Ziel erreicht!', completedBody: 'Du hast dein Ziel von {{amount}} erreicht.', createAnother: 'Weiteres Ziel erstellen', returnGoals: 'Zurück zu den Zielen' },
  pt: { title: 'Objetivos', active: 'Ativos', completed: 'Concluídos', archived: 'Arquivados', add: 'Criar objetivo', edit: 'Editar objetivo', empty: 'Crie um objetivo que se adapte ao seu plano.', description: 'Descrição (opcional)', name: 'Nome do objetivo', target: 'Montante objetivo', saved: 'Já poupado', date: 'Data objetivo', next: 'Seguinte', back: 'Voltar', save: 'Guardar objetivo', update: 'Atualizar objetivo', chooseCategory: 'Escolha uma categoria', chooseStyle: 'Escolha um ícone e uma cor', enterDetails: 'Introduza os detalhes', review: 'Revisão e lembrete', priority: 'Prioridade', reminder: 'Lembrete de contribuição', noReminder: 'Sem lembrete', weekly: 'Semanal', monthly: 'Mensal', once: 'Uma vez', contribution: 'Adicionar contribuição', contributionAmount: 'Montante da contribuição', contributionNote: 'Nota (opcional)', history: 'Histórico de contribuições', noHistory: 'Ainda não existem contribuições.', pause: 'Pausar', resume: 'Retomar', archive: 'Arquivar', delete: 'Eliminar', markComplete: 'Marcar como concluído', deleteConfirm: 'Eliminar este objetivo e o histórico de contribuições?', savedOf: '{{saved}} poupados de {{target}}', due: 'Vence em {{date}}', requiredMonthly: 'Pode precisar de {{amount}} por mês', requiredWeekly: '{{amount}} por semana', projected: 'Previsto para {{date}}', statuses: { on_track: 'No bom caminho', adjustment_needed: 'Precisa de um pequeno ajuste', unrealistic: 'Atualmente irrealista', completed: 'Concluído', paused: 'Em pausa', active: 'Ativo', archived: 'Arquivado' }, priorities: { essential: 'Alta', important: 'Média', optional: 'Baixa' }, categories: categories.pt, validation: { title: 'Introduza um nome para o objetivo.', target: 'Introduza um montante objetivo superior a zero.', saved: 'Introduza um montante poupado válido.', date: 'Escolha hoje ou uma data futura.', contribution: 'Introduza um montante de contribuição válido.' }, completedTitle: 'Objetivo concluído!', completedBody: 'Atingiu o objetivo de {{amount}}.', createAnother: 'Criar outro objetivo', returnGoals: 'Voltar aos objetivos' },
  it: { title: 'Obiettivi', active: 'Attivi', completed: 'Completati', archived: 'Archiviati', add: 'Crea obiettivo', edit: 'Modifica obiettivo', empty: 'Crea un obiettivo adatto al tuo piano.', description: 'Descrizione (facoltativa)', name: 'Nome obiettivo', target: 'Importo obiettivo', saved: 'Già risparmiato', date: 'Data obiettivo', next: 'Avanti', back: 'Indietro', save: 'Salva obiettivo', update: 'Aggiorna obiettivo', chooseCategory: 'Scegli una categoria', chooseStyle: 'Scegli icona e colore', enterDetails: 'Inserisci i dettagli', review: 'Revisione e promemoria', priority: 'Priorità', reminder: 'Promemoria contributo', noReminder: 'Nessun promemoria', weekly: 'Settimanale', monthly: 'Mensile', once: 'Una volta', contribution: 'Aggiungi contributo', contributionAmount: 'Importo contributo', contributionNote: 'Nota (facoltativa)', history: 'Storico contributi', noHistory: 'Nessun contributo registrato.', pause: 'Metti in pausa', resume: 'Riprendi', archive: 'Archivia', delete: 'Elimina', markComplete: 'Segna come completato', deleteConfirm: 'Eliminare questo obiettivo e lo storico contributi?', savedOf: '{{saved}} risparmiati su {{target}}', due: 'Scadenza {{date}}', requiredMonthly: 'Potrebbero servire {{amount}} al mese', requiredWeekly: '{{amount}} a settimana', projected: 'Previsto per {{date}}', statuses: { on_track: 'In linea', adjustment_needed: 'Serve un piccolo aggiustamento', unrealistic: 'Attualmente irrealistico', completed: 'Completato', paused: 'In pausa', active: 'Attivo', archived: 'Archiviato' }, priorities: { essential: 'Alta', important: 'Media', optional: 'Bassa' }, categories: categories.it, validation: { title: 'Inserisci un nome per l’obiettivo.', target: 'Inserisci un importo obiettivo maggiore di zero.', saved: 'Inserisci un importo risparmiato valido.', date: 'Scegli oggi o una data futura.', contribution: 'Inserisci un contributo valido.' }, completedTitle: 'Obiettivo completato!', completedBody: 'Hai raggiunto il tuo obiettivo di {{amount}}.', createAnother: 'Crea un altro obiettivo', returnGoals: 'Torna agli obiettivi' },
  nl: { title: 'Doelen', active: 'Actief', completed: 'Voltooid', archived: 'Gearchiveerd', add: 'Doel maken', edit: 'Doel bewerken', empty: 'Maak een doel dat bij je plan past.', description: 'Beschrijving (optioneel)', name: 'Naam van doel', target: 'Doelbedrag', saved: 'Al gespaard', date: 'Streefdatum', next: 'Volgende', back: 'Terug', save: 'Doel opslaan', update: 'Doel bijwerken', chooseCategory: 'Kies een categorie', chooseStyle: 'Kies een pictogram en kleur', enterDetails: 'Voer doelgegevens in', review: 'Controle en herinnering', priority: 'Prioriteit', reminder: 'Bijdrageherinnering', noReminder: 'Geen herinnering', weekly: 'Wekelijks', monthly: 'Maandelijks', once: 'Eenmalig', contribution: 'Bijdrage toevoegen', contributionAmount: 'Bijdragebedrag', contributionNote: 'Notitie (optioneel)', history: 'Bijdragegeschiedenis', noHistory: 'Nog geen bijdragen vastgelegd.', pause: 'Pauzeren', resume: 'Hervatten', archive: 'Archiveren', delete: 'Verwijderen', markComplete: 'Als voltooid markeren', deleteConfirm: 'Dit doel en de bijdragegeschiedenis verwijderen?', savedOf: '{{saved}} gespaard van {{target}}', due: 'Vervalt {{date}}', requiredMonthly: 'Mogelijk {{amount}} per maand nodig', requiredWeekly: '{{amount}} per week', projected: 'Verwacht {{date}}', statuses: { on_track: 'Op schema', adjustment_needed: 'Kleine aanpassing nodig', unrealistic: 'Momenteel onrealistisch', completed: 'Voltooid', paused: 'Gepauzeerd', active: 'Actief', archived: 'Gearchiveerd' }, priorities: { essential: 'Hoog', important: 'Gemiddeld', optional: 'Laag' }, categories: categories.nl, validation: { title: 'Voer een naam voor het doel in.', target: 'Voer een doelbedrag groter dan nul in.', saved: 'Voer een geldig gespaard bedrag in.', date: 'Kies vandaag of een toekomstige datum.', contribution: 'Voer een geldig bijdragebedrag in.' }, completedTitle: 'Doel voltooid!', completedBody: 'Je hebt je doel van {{amount}} bereikt.', createAnother: 'Nog een doel maken', returnGoals: 'Terug naar doelen' },
  tr: { title: 'Hedefler', active: 'Aktif', completed: 'Tamamlandı', archived: 'Arşivlendi', add: 'Hedef oluştur', edit: 'Hedefi düzenle', empty: 'Planınıza uygun bir hedef oluşturun.', description: 'Açıklama (isteğe bağlı)', name: 'Hedef adı', target: 'Hedef tutarı', saved: 'Zaten biriken', date: 'Hedef tarihi', next: 'İleri', back: 'Geri', save: 'Hedefi kaydet', update: 'Hedefi güncelle', chooseCategory: 'Kategori seçin', chooseStyle: 'Simge ve renk seçin', enterDetails: 'Hedef ayrıntılarını girin', review: 'İnceleme ve hatırlatma', priority: 'Öncelik', reminder: 'Katkı hatırlatması', noReminder: 'Hatırlatma yok', weekly: 'Haftalık', monthly: 'Aylık', once: 'Bir kez', contribution: 'Katkı ekle', contributionAmount: 'Katkı tutarı', contributionNote: 'Not (isteğe bağlı)', history: 'Katkı geçmişi', noHistory: 'Henüz katkı kaydedilmedi.', pause: 'Duraklat', resume: 'Devam et', archive: 'Arşivle', delete: 'Sil', markComplete: 'Tamamlandı olarak işaretle', deleteConfirm: 'Bu hedef ve katkı geçmişi silinsin mi?', savedOf: '{{target}} tutarın {{saved}} kadarı birikti', due: 'Vade {{date}}', requiredMonthly: 'Ayda {{amount}} gerekebilir', requiredWeekly: 'Haftada {{amount}}', projected: 'Tahmini {{date}}', statuses: { on_track: 'Yolunda', adjustment_needed: 'Küçük ayarlama gerekli', unrealistic: 'Şu anda gerçekçi değil', completed: 'Tamamlandı', paused: 'Duraklatıldı', active: 'Aktif', archived: 'Arşivlendi' }, priorities: { essential: 'Yüksek', important: 'Orta', optional: 'Düşük' }, categories: categories.tr, validation: { title: 'Bir hedef adı girin.', target: 'Sıfırdan büyük bir hedef tutarı girin.', saved: 'Geçerli bir birikim tutarı girin.', date: 'Bugünü veya gelecek bir tarihi seçin.', contribution: 'Geçerli bir katkı tutarı girin.' }, completedTitle: 'Hedef tamamlandı!', completedBody: '{{amount}} tutarındaki hedefinize ulaştınız.', createAnother: 'Başka hedef oluştur', returnGoals: 'Hedeflere dön' },
} as const;

export const goalSupplementTranslations = {
  en: { allCategories: 'All categories', sort: { priority: 'Priority', date: 'Date', progress: 'Progress' }, vectors: vectors.en, colors: colors.en, reminderDate: 'Reminder date', reminderDateValidation: 'Choose today or a future reminder date.', completeConfirm: 'Mark this goal complete without changing the saved amount?' },
  fr: { allCategories: 'Toutes les catégories', sort: { priority: 'Priorité', date: 'Date', progress: 'Progression' }, vectors: vectors.fr, colors: colors.fr, reminderDate: 'Date du rappel', reminderDateValidation: 'Choisissez une date de rappel actuelle ou future.', completeConfirm: 'Marquer cet objectif comme terminé sans modifier le montant épargné ?' },
  ar: { allCategories: 'كل الفئات', sort: { priority: 'الأولوية', date: 'التاريخ', progress: 'التقدم' }, vectors: vectors.ar, colors: colors.ar, reminderDate: 'تاريخ التذكير', reminderDateValidation: 'اختر اليوم أو تاريخ تذكير مستقبلي.', completeConfirm: 'تحديد هذا الهدف كمكتمل دون تغيير المبلغ المدخر؟' },
  es: { allCategories: 'Todas las categorías', sort: { priority: 'Prioridad', date: 'Fecha', progress: 'Progreso' }, vectors: vectors.es, colors: colors.es, reminderDate: 'Fecha del recordatorio', reminderDateValidation: 'Elige hoy o una fecha futura.', completeConfirm: '¿Marcar este objetivo como completado sin cambiar el importe ahorrado?' },
  de: { allCategories: 'Alle Kategorien', sort: { priority: 'Priorität', date: 'Datum', progress: 'Fortschritt' }, vectors: vectors.de, colors: colors.de, reminderDate: 'Erinnerungsdatum', reminderDateValidation: 'Wähle heute oder ein zukünftiges Erinnerungsdatum.', completeConfirm: 'Dieses Ziel als abgeschlossen markieren, ohne den Sparbetrag zu ändern?' },
  pt: { allCategories: 'Todas as categorias', sort: { priority: 'Prioridade', date: 'Data', progress: 'Progresso' }, vectors: vectors.pt, colors: colors.pt, reminderDate: 'Data do lembrete', reminderDateValidation: 'Escolha hoje ou uma data futura.', completeConfirm: 'Marcar este objetivo como concluído sem alterar o montante poupado?' },
  it: { allCategories: 'Tutte le categorie', sort: { priority: 'Priorità', date: 'Data', progress: 'Progresso' }, vectors: vectors.it, colors: colors.it, reminderDate: 'Data promemoria', reminderDateValidation: 'Scegli oggi o una data futura.', completeConfirm: 'Segnare l’obiettivo come completato senza modificare l’importo risparmiato?' },
  nl: { allCategories: 'Alle categorieën', sort: { priority: 'Prioriteit', date: 'Datum', progress: 'Voortgang' }, vectors: vectors.nl, colors: colors.nl, reminderDate: 'Herinneringsdatum', reminderDateValidation: 'Kies vandaag of een toekomstige herinneringsdatum.', completeConfirm: 'Dit doel als voltooid markeren zonder het gespaarde bedrag te wijzigen?' },
  tr: { allCategories: 'Tüm kategoriler', sort: { priority: 'Öncelik', date: 'Tarih', progress: 'İlerleme' }, vectors: vectors.tr, colors: colors.tr, reminderDate: 'Hatırlatma tarihi', reminderDateValidation: 'Bugünü veya gelecek bir tarihi seçin.', completeConfirm: 'Birikim tutarını değiştirmeden bu hedef tamamlansın mı?' },
} as const;

Object.assign(goalTranslations.en, goalSupplementTranslations.en);
Object.assign(goalTranslations.fr, goalSupplementTranslations.fr);
Object.assign(goalTranslations.ar, goalSupplementTranslations.ar);
Object.assign(goalTranslations.es, goalSupplementTranslations.es);
Object.assign(goalTranslations.de, goalSupplementTranslations.de);
Object.assign(goalTranslations.pt, goalSupplementTranslations.pt);
Object.assign(goalTranslations.it, goalSupplementTranslations.it);
Object.assign(goalTranslations.nl, goalSupplementTranslations.nl);
Object.assign(goalTranslations.tr, goalSupplementTranslations.tr);
